version: "3.9"
services:

    # Backend 
    api:
        container_name: api
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        restart: always 
        working_dir: /app
        volumes:
            - ./server:/app
            - /app/node_modules
        ports:
            - "5000:5000"
        env_file:
            - .env

    # client
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - ./client:/app
            - /app/node_modules
        ports:
            - "3000:3000"
